version: '3.1'

services:
    web:
      image: nginx
      volumes:
       - ./nginx/conf:/etc/nginx
       - ./nginx/src:/usr/share/nginx/html
      healthcheck:
        test: curl --fail http://localhost:8080 || exit 1
        interval: 60s
        retries: 5
        start_period: 20s
        timeout: 10s
      ports:
       - "8083:80"
      environment:
       - NGINX_HOST=foobar.com
       - NGINX_PORT=80